[projects.digitiva]
name = "digitiva"

[services.web]
root = "web"
start = "npm run start"
build = "npm run build"
env = ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"]
domains = []
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[services.api]
root = "api"
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"
build = "pip install -r requirements.txt"
env = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_BUCKET", "IDEASOFT_BASE_URL", "IDEASOFT_API_KEY", "DATABASE_URL"]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[services.n8n]
dockerImage = "docker.n8n.io/n8nio/n8n:latest"
env = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_BUCKET", "IDEASOFT_BASE_URL", "IDEASOFT_API_KEY", "DATABASE_URL", "REDIS_URL"]
restartPolicyType = "ALWAYS"

[plugins.postgres]
[plugins.redis]